# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Se ejecuta al hacer push a la rama "main" (o "master", verifica tu rama principal)
  push:
    branches: ["main"]

  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite una sola ejecución concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Trabajo único de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube la carpeta 'dist' que se genera en la raíz
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4